// swift-tools-version: 5.9
import PackageDescription

#if os(macOS)
let mappingSources = ["MappingPackage.swift", "MappingRules.swift", "MappingStore.swift", "MappingService.swift"]
let mappingTests = ["MappingPackageTests.swift", "MappingServiceTests.swift"]
let mappingExcludes: [String] = []
let mappingTestExcludes: [String] = []
#else
// CryptoKit and URLSession host tests run on the macOS release runner.
let mappingSources: [String] = []
let mappingTests: [String] = []
let mappingExcludes = ["MappingPackage.swift", "MappingRules.swift", "MappingStore.swift", "MappingService.swift"]
let mappingTestExcludes = ["MappingPackageTests.swift", "MappingServiceTests.swift"]
#endif

// Host tests compile the same Foundation-based sources used by the iOS target.
let package = Package(
    name: "TakupokeParsing",
    platforms: [.macOS(.v12), .iOS(.v16)],
    dependencies: [
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", revision: "22787ffb59de99e5dc1fbfe80b19c97a904ad48d"),
        .package(url: "https://github.com/groue/GRDB.swift.git", revision: "b83108d10f42680d78f23fe4d4d80fc88dab3212")
    ],
    targets: [
        .target(name: "TakupokeParsing", dependencies: ["ZIPFoundation", .product(name: "GRDB", package: "GRDB.swift")], path: "Takupoke",
                exclude: [
                    "Assets.xcassets",
                    "AppIcon.icon",
                    "Info.plist",
                    "PrivacyInfo.xcprivacy",
                    "ThirdPartyNotices.txt",
                    "TakupokeApp.swift",
                    "ContentView.swift",
                    "SettingsView.swift",
                    "HomeView.swift",
                    "MaterialAccess.swift",
                    "ScopedMaterialSelection.swift",
                    "MaterialWorker+Analysis.swift",
                    "MaterialWorker+Provider.swift",
                    "MaterialsModel.swift",
                    "MaterialsModel+Updates.swift",
                    "SpecialSchedulesModel+Updates.swift",
                    "MaterialsView.swift",
                    "MaterialDocumentPicker.swift",
                    "SpecialScheduleAnalysisView.swift",
                    "ChangeAnalysisView.swift",
                    "ChangePreviewView.swift",
                    "WebPDFDownloader.swift",
                    "PDFAnalysisView.swift",
                    "PDFLessonDetail.swift",
                    "SavedPDFView.swift",
                    "TimetableView.swift",
                    "TimetableView+Grid.swift",
                    "TimetableView+Layout.swift",
                    "TimetableView+Cards.swift",
                    "TimetableView+Times.swift",
                    "TimetableView+Changes.swift",
                    "TimetableView+Navigation.swift",
                    "TimetableView+Details.swift",
                    "TimetableClassSelection.swift",
                    "SpecialSchedulesModel.swift",
                    "SpecialSchedulesModel+Startup.swift",
                    "SpecialSchedulesModel+Analysis.swift",
                    "SpecialSchedulesModel+Provider.swift",
                    "SchoolEventsModel.swift",
                    "SchoolEventsView.swift",
                    "MappingOIDC.swift",
                    "MappingModel.swift",
                    "MappingSettingsView.swift",
                    "LinksModel.swift",
                    "LinksView.swift",
                    "SafariLinkView.swift",
                    "LinkRow.swift",
                ] + mappingExcludes,
                sources: [
                    "LocalMaterialDatabase.swift",
                    "LocalMaterialDatabase+Current.swift",
                    "PDFAnalysis.swift",
                    "PDFParseError.swift",
                    "PDFGrid.swift",
                    "PDFSchoolParser+Timetable.swift",
                    "PDFSchoolParser+Events.swift",
                    "LocalMaterialDatabase+Legacy.swift",
                    "LocalMaterialDatabase+Records.swift",
                    "LocalMaterialDatabase+Schema.swift",
                    "LegacyDatabaseMigration.swift",
                    "ChangeNormalizer.swift",
                    "ChangeAnalysis.swift",
                    "XLSXReader.swift",
                    "BoundedXML.swift",
                    "MaterialLibrary.swift",
                    "MaterialModels.swift",
                    "SelectedFileSource.swift",
                    "FileRefreshDiagnostics.swift",
                    "SelectedFilePresenter.swift",
                    "SelectedFileObservation.swift",
                    "SelectedFileMonitor.swift",
                    "MaterialLibrary+Validation.swift",
                    "TimetableLessonNames.swift",
                    "PDFSchoolParser.swift",
                    "PDFKitReader.swift",
                    "PDFCharacterGeometry.swift",
                    "PDFKitReader+Diagnostics.swift",
                    "PDFPathReader.swift",
                    "PDFTextGeometry.swift",
                    "PDFUnicodeMap.swift",
                    "PDFDrawnTextReader.swift",
                    "PDFDrawnTextReader+Fonts.swift",
                    "PDFDiagnostics.swift",
                    "PDFFullReadDiagnostic.swift",
                    "PDFFullDiagnosticEncoding.swift",
                    "SchoolDate.swift",
                    "SchoolDataRetention.swift",
                    "TimetableSchedule.swift",
                    "TimetableSchedule+Blocks.swift",
                    "TimetableSchedule+Events.swift",
                    "TimetableSchedule+Weeks.swift",
                    "SpecialSchedule.swift",
                    "SpecialScheduleParser.swift",
                    "SpecialScheduleParser+Times.swift",
                    "SpecialScheduleParser+Pages.swift",
                    "SpecialScheduleStore.swift",
                    "SpecialScheduleRecord.swift",
                    "SchoolEventsAPI.swift",
                    "SchoolEventsStore.swift",
                    "LinksAPI.swift",
                    "LinksStore.swift",
                    "LinkSearch.swift",
                ] + mappingSources),
        .testTarget(name: "ParsingTests", dependencies: ["TakupokeParsing", "ZIPFoundation", .product(name: "GRDB", package: "GRDB.swift")], path: "tests",
                    exclude: [
                    "MaterialLibraryChecks.swift",
                    "WebPDFChecks.swift",
                    "test_distribution.py",
                ] + mappingTestExcludes,
                    sources: [
                    "FileRefreshTests.swift",
                    "ParsingTests.swift",
                    "ParsingTests+Normalization.swift",
                    "ParsingTests+Workbook.swift",
                    "ParsingTests+Preview.swift",
                    "ParsingTests+Persistence.swift",
                    "TimetableNameTests.swift",
                    "PDFParsingTests.swift",
                    "PDFParsingTests+Timetable.swift",
                    "PDFParsingTests+Diagnostics.swift",
                    "PDFParsingTests+Events.swift",
                    "PDFParsingTests+PDFKit.swift",
                    "PDFTextGeometryTests.swift",
                    "LocalDatabaseTests.swift",
                    "LocalDatabaseTests+Legacy.swift",
                    "LocalDatabaseTests+Current.swift",
                    "SchoolDateTests.swift",
                    "SchoolDataRetentionTests.swift",
                    "TimetableScheduleTests.swift",
                    "TimetableScheduleTests+Changes.swift",
                    "TimetableScheduleTests+Blocks.swift",
                    "TimetableScheduleTests+Events.swift",
                    "SpecialScheduleTests.swift",
                    "SpecialScheduleTests+Fixtures.swift",
                    "SpecialScheduleTests+Persistence.swift",
                    "SchoolEventsAPITests.swift",
                    "LinksTests.swift",
                ] + mappingTests, resources: [.copy("fixtures")])
    ]
)
