// swift-tools-version: 5.9
import PackageDescription

#if os(macOS)
let mappingSources = ["TimetableTimesService.swift", "MappingPackage.swift", "MappingStore.swift", "MappingService.swift"]
let mappingTests = ["TimetableTimesServiceTests.swift", "MappingPackageTests.swift", "MappingServiceTests.swift"]
let mappingExcludes: [String] = []
let mappingTestExcludes: [String] = []
#else
// CryptoKit and URLSession host tests run on the macOS release runner.
let mappingSources: [String] = []
let mappingTests: [String] = []
let mappingExcludes = ["TimetableTimesService.swift", "MappingPackage.swift", "MappingStore.swift", "MappingService.swift"]
let mappingTestExcludes = ["TimetableTimesServiceTests.swift", "MappingPackageTests.swift", "MappingServiceTests.swift"]
#endif

// Host tests compile the same Foundation-based sources used by the iOS target.
let package = Package(
    name: "TakupokeParsing",
    platforms: [.macOS(.v12), .iOS("26.0")],
    dependencies: [
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", revision: "22787ffb59de99e5dc1fbfe80b19c97a904ad48d"),
        .package(url: "https://github.com/groue/GRDB.swift.git", revision: "b83108d10f42680d78f23fe4d4d80fc88dab3212"),
        .package(url: "https://github.com/apple/swift-crypto.git", revision: "da9d28d69ebe3894b18376c8f2395c2f37b8448f")
    ],
    targets: [
        .target(name: "TakupokeParsing", dependencies: ["ZIPFoundation", .product(name: "GRDB", package: "GRDB.swift"), .product(name: "Crypto", package: "swift-crypto", condition: .when(platforms: [.linux]))], path: "Takupoke",
                exclude: [
                    "Assets.xcassets",
                    "AppIcon.icon",
                    "Info.plist",
                    "PrivacyInfo.xcprivacy",
                    "LicenseDocuments",
                    "OpenSourceLicensesView.swift",
                    "TakupokeApp.swift",
                    "ContentView.swift",
                    "ApplicationData.swift", "BackgroundRefresh.swift", "TimetableTimesModel.swift",
                    "ScheduleNotifications.swift", "NotificationSettingsView.swift",
                    "SettingsView.swift",
                    "HomeView.swift",
                    "HomeTodayView.swift", "HomeLessonRow.swift",
                    "TimetablePresentation.swift", "TimetablePresentation+Details.swift",
                    "LoadingRow.swift",
                    "AboutView.swift",
                    "UsageHelpView.swift",
                    "AccountDataSettingsView.swift",
                    "SetupView.swift",
                    "AccountDataModel.swift",
                    "LegalDocumentView.swift",
                    "LegalDocuments",
                    "MaterialAccess.swift",
                    "ScopedMaterialSelection.swift",
                    "MaterialWorker+Analysis.swift",
                    "MaterialWorker+Provider.swift",
                    "MaterialsModel.swift",
                    "MaterialsModel+Updates.swift",
                    "SpecialSchedulesModel+Updates.swift",
                    "MaterialsView.swift", "MaterialsView+FileSummary.swift",
                    "MaterialDocumentPicker.swift",
                    "GuidedDocumentPicker.swift",
                    "SpecialScheduleAnalysisView.swift",
                    "ChangeAnalysisView.swift",
                    "ChangePreviewView.swift",
                    "WebPDFDownloader.swift",
                    "PDFAnalysisView.swift", "SystemLanguageRecoveryProvider.swift", "PDFRecoveryRecognition.swift",
                    "PDFRecoveryCoordinator.swift", "PDFRecoveryView.swift", "LocalRecoveryModelManager.swift", "LocalLlamaRecoveryProvider.swift", "CoreAIRecoveryProvider.swift",
                    "PDFLessonDetail.swift",
                    "SavedPDFView.swift",
                    "TimetableView.swift", "TimetableView+WeekSection.swift",
                    "TimetableView+Grid.swift", "TimetableView+GridHeaders.swift", "TimetableView+DayColumns.swift",
                    "TimetableView+Layout.swift",
                    "TimetableView+Cards.swift",
                    "TimetableView+Times.swift",
                    "TimetableView+Changes.swift",
                    "TimetableView+Navigation.swift",
                    "TimetableView+Details.swift",
                    "TimetableClassSelection.swift",
                    "SpecialSchedulesModel.swift",
                    "SpecialSchedulesModel+Startup.swift",
                    "SpecialSchedulesModel+Analysis.swift",
                    "SpecialSchedulesModel+Provider.swift",
                    "SchoolEventsModel.swift",
                    "SchoolEventsView.swift",
                    "MappingOIDC.swift",
                    "MappingModel.swift",
                    "MappingSettingsView.swift",
                    "LinksModel.swift",
                    "LinksView.swift",
                    "SafariLinkView.swift",
                    "LinkRow.swift",
                ] + mappingExcludes,
                sources: [
                    "MainColor.swift",
                    "LocalMaterialDatabase.swift",
                    "LocalMaterialDatabase+Current.swift", "LocalMaterialDatabase+Snapshot.swift",
                    "PDFAnalysis.swift", "RecoveryModels.swift", "RecoveryValidator.swift", "RecoveryPromptCatalog.swift", "RecoveryModelStore.swift", "RecoveryEngine.swift", "RecoveryStructure.swift", "RecoveryDocumentBuilder.swift", "RecoveryConversion.swift", "RecoveryRasterGrid.swift",
                    "PDFParseError.swift",
                    "PDFGrid.swift",
                    "PDFSchoolParser+Timetable.swift",
                    "PDFSchoolParser+Events.swift",
                    "LocalMaterialDatabase+Legacy.swift",
                    "LocalMaterialDatabase+Records.swift",
                    "LocalMaterialDatabase+Schema.swift",
                    "LegacyDatabaseMigration.swift",
                    "ChangeNormalizer.swift", "ChangeNormalizer+Dates.swift",
                    "ChangeAnalysis.swift",
                    "XLSXReader.swift", "XLSXReader+Worksheet.swift",
                    "BoundedXML.swift",
                    "MaterialLibrary.swift", "MaterialLibrary+Analysis.swift",
                    "MaterialModels.swift",
                    "SelectedFileSource.swift",
                    "FileRefreshDiagnostics.swift",
                    "SelectedFilePresenter.swift",
                    "SelectedFileObservation.swift",
                    "SelectedFileMonitor.swift",
                    "MaterialLibrary+Validation.swift",
                    "TimetableLessonNames.swift",
                    "MappingRules.swift", "MappingRules+Changes.swift", "MappingModels.swift",
                    "PDFSchoolParser.swift",
                    "PDFKitReader.swift",
                    "PDFCharacterGeometry.swift",
                    "PDFKitReader+Diagnostics.swift",
                    "PDFPathReader.swift",
                    "PDFTextGeometry.swift",
                    "PDFUnicodeMap.swift",
                    "PDFDrawnTextReader.swift",
                    "PDFDrawnTextReader+Fonts.swift",
                    "PDFDiagnostics.swift",
                    "PDFFullReadDiagnostic.swift",
                    "PDFFullDiagnosticEncoding.swift",
                    "MaterialPickerLayout.swift",
                    "SchoolDate.swift", "JapaneseDateDisplay.swift",
                    "SchoolDataRetention.swift",
                    "ScheduleNotificationSnapshot.swift",
                    "TimetableSchedule.swift",
                    "TimetableDaySchedule.swift", "TimetableTimes.swift",
                    "TimetableSchedule+Blocks.swift",
                    "TimetableSchedule+Events.swift",
                    "TimetableSchedule+Weeks.swift",
                    "SpecialSchedule.swift",
                    "SpecialScheduleParser.swift",
                    "SpecialScheduleParser+Times.swift",
                    "SpecialScheduleParser+Pages.swift",
                    "SpecialScheduleStore.swift",
                    "SpecialScheduleRecord.swift",
                    "SchoolEventsAPI.swift",
                    "SchoolEventsStore.swift",
                    "LinksAPI.swift",
                    "LinksStore.swift",
                    "LinkSearch.swift",
                ] + mappingSources, resources: [.copy("RecoveryPromptResources/field-extraction-v4.txt")]),
        .testTarget(name: "ParsingTests", dependencies: ["TakupokeParsing", "ZIPFoundation", .product(name: "GRDB", package: "GRDB.swift")], path: "tests",
                    exclude: [
                    "ui",
                    "MaterialLibraryChecks.swift",
                    "WebPDFChecks.swift",
                    "test_distribution.py",
                    "test_parallel_build.py",
                    "test_release_gate.py",
                    "test_timed_command.py",
                    "test_ui_test_manifest.py",
                ] + mappingTestExcludes,
                    sources: [
                    "MainColorTests.swift",
                    "FileRefreshTests.swift",
                    "ParsingTests.swift",
                    "ParsingTests+Normalization.swift",
                    "ParsingTests+Workbook.swift",
                    "ParsingTests+Preview.swift",
                    "ParsingTests+Persistence.swift",
                    "TimetableNameTests.swift", "MappingRulesTests.swift",
                    "PDFParsingTests.swift", "RecoveryTests.swift", "RecoveryRecertificationTests.swift", "RecoveryBuilderTests.swift", "RecoveryStructureTests.swift", "RecoveryPromptCatalogTests.swift",
                    "PDFParsingTests+Timetable.swift",
                    "PDFParsingTests+Diagnostics.swift",
                    "PDFParsingTests+Events.swift",
                    "PDFParsingTests+PDFKit.swift",
                    "PDFTextGeometryTests.swift",
                    "LocalDatabaseTests.swift",
                    "LocalDatabaseTests+Legacy.swift",
                    "LocalDatabaseTests+Current.swift",
                    "MaterialPickerLayoutTests.swift",
                    "SchoolDateTests.swift", "JapaneseDateDisplayTests.swift",
                    "SchoolDataRetentionTests.swift",
                    "ScheduleNotificationTests.swift",
                    "TimetableScheduleTests.swift",
                    "HomeScheduleTests.swift", "TimetableTimesTests.swift",
                    "TimetableScheduleTests+Changes.swift",
                    "TimetableScheduleTests+Blocks.swift",
                    "TimetableScheduleTests+Events.swift",
                    "SpecialScheduleTests.swift",
                    "SpecialScheduleTests+Fixtures.swift",
                    "SpecialScheduleTests+Persistence.swift",
                    "SchoolEventsAPITests.swift",
                    "LinksTests.swift",
                ] + mappingTests, resources: [.copy("fixtures")])
    ]
)
